/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.federicocardara.cryptoutils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CryptoUtilsTest {
    @Test void someLibraryMethodReturnsTrue() {
        CryptoUtils classUnderTest = new CryptoUtils();

    }
}
