/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.federicocardara.cryptoutils;

import cat.uvic.teknos.m09.federicocardara.cryptoutils.exceptions.CryptUtilsException;

public class CryptoUtils {

    public static DigestResult hash(byte[] message) {
        try {

        } catch (Exception exception) {
            throw new CryptUtilsException("srhnvoeurnñq", exception);
        }
        return null;
    }

    /**
     * 
     * @param plainText
     * @param password
     * @return
     */
    public static byte[] encrypt(byte[] plainText, String password) {
        return null;
    }
}
